import "./globals.css";
import { League_Spartan } from "next/font/google";

const inter = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Mentor | Room homepage",
  description: "Generated by create next app",
	viewport: "width=device-width, initial-scale=1.0"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}
        min-h-scree
        flex
        flex-col
        items-center
        justify-center
      `}>{children}</body>
    </html>
  );
}
